name: nomisal_app
description: An application to integrate dart entities/models in nomisal style.
version: 0.0.11
repository: https://github.com/nomagicisreal/nomisal_app

environment:
  sdk: ^3.1.4

#dependencies:
dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
