name: nomisal_app
description: An application for nomisal to integrate dart entities/models.
version: 0.0.4
repository: https://github.com/nomagicisreal/nomisal_app

environment:
  sdk: ^3.1.4

dependencies:
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  lints: ^3.0.0
  test: ^1.21.0
